model: 
  encoder: ResNet18
  decoder: UnetDecoder

loss:
  depth: 
    - MAE
  road_segmentation:
    - BinaryCrossEntropyLoss

metrics:
  depth:
    - MAE
  road_segmentation:
    - ConfusionMatrix
