name: 00_ResNet18_epoch20
device: cuda
dataset:
  dataset_name: KittiDataset
  task_transform:
    input: 
      - Crop
    # depth:
    #   - Crop
    road_detection:
      - Crop
  task_paths:
    input: "./data/kitti/input"
    # depth: "./data/kitti/depth" # for visualization purposes
    road_detection: "./data/kitti/semantic_segmentation"
  task_sample_list_path_train:
    # depth: "./data/kitti/sample_lists/train/depth_sample_list.txt"
    road_detection: "./data/kitti/sample_lists/train/semseg_sample_list.txt"
  task_sample_list_path_val:
    road_detection: "./data/kitti/sample_lists/val/semseg_sample_list.txt"
    # depth: "./data/kitti/sample_lists/train/depth_sample_list.txt" # for visualization purposes

train:
  dataloader:
    batch_size: 32
    shuffle: True
    num_workers: 1

early_stopping:
  patience: 5
  min_delta: 0.01

epochs: 40

model:
  weights_file_path: ../run_info/00_ResNet18_depth_estimation_kitti/best_model.pth
  encoder:
    name: ResNet18
    freeze_epoch: 0
    unfreeze_epoch: -1
    pretrained_regex: ["*"]
  depth_decoder:
    name: UnetDepthDecoder
    in_channels: 512
    channel_scale_factors: [2, 4, 8, 8]
    out_channels: 1
    freeze_epoch: 0
    unfreeze_epoch: -1
    pretrained_regex: ["*"]
  road_detection_decoder:
    name: UnetRoadDetectionDecoder
    in_channels: 512
    channel_scale_factors: [2, 4, 8, 8]
    out_channels: 1
    freeze_epoch: -1
    unfreeze_epoch: 0

prediction_postprocess: # used only in eval
  - depth:
    - min_depth: 0.0
    - max_depth: 90.0
  - road_detection: # None

loss:
  road_detection:
    - BinaryCrossEntropyLoss:
      - lambda_factor: 1.0

optimizer:
  name: Adam
  lr: 1e-4


eval:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1

metrics:
  road_detection:
    - IoU
    - Precision
    - Recall
    - FalsePositiveRate
    - TrueNegativeRate
    - F1Score

save_path: ../run_info/