name: 00_ResNet18_epoch20
device: cuda
dataset:
  dataset_name: KittiDataset
  task_transform:
    input: 
      - Crop
    road_detection:
      - Crop
  task_paths:
    input: "./data/kitti/input"
    road_detection: "./data/kitti/semantic_segmentation"

train:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1
  aggregators_savers:
    LossAggregator: LossSaver # bind aggregator to saver
  savers:
    LossSaver: LossAggregator # bind aggregator to saver

eval:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1

model:
  encoder:
    name: ResNet18
    pretrained: True
    freeze_epoch: 0
    unfreeze_epoch: 10
  decoder:
    road_detection:
      name: UnetRoadDetectionDecoder
      in_channels: 512
      channel_scale_factors: [2, 4, 8, 8]
      out_channels: 1
      freeze_epoch: None
      unfreeze_epoch: None

loss:
  road_detection:
    - BinaryCrossEntropyLoss

optimizer:
  name: Adam
  lr: 1e-4

epochs: 20

metrics:
  road_detection:
    - #TODO:

save_path: ../run_info