name: 00_ResNet18_epoch20
device: cuda
dataset:
  dataset_name: KittiDataset
  task_transform:
    input: 
      - Crop
    road_detection:
      - Crop
  task_paths:
    input: "./data/kitti/input"
    road_detection: "./data/kitti/semantic_segmentation"

train:
  dataloader:
    batch_size: 2
    shuffle: False
    num_workers: 1
  aggregators_savers:
    LossAggregator: LossSaver # bind aggregator to saver
  savers:
    LossSaver: LossAggregator # bind aggregator to saver

epochs: 30


model:
  encoder:
    name: ResNet18
    pretrained: True
    freeze_epoch: -1
    unfreeze_epoch: -1
  depth_decoder:
    name: UnetDepthDecoder
    in_channels: 512
    channel_scale_factors: [2, 4, 8, 8]
    out_channels: 1
    freeze_epoch: None
    unfreeze_epoch: None
  road_detection_decoder:
    name: UnetRoadDetectionDecoder
    in_channels: 512
    channel_scale_factors: [2, 4, 8, 8]
    out_channels: 1
    freeze_epoch: None
    unfreeze_epoch: None

prediction_processors: [road_detection]

loss:
  road_detection:
    - BinaryCrossEntropyLoss

optimizer:
  name: Adam
  lr: 1e-4


eval:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1

metrics:
  road_detection:
    - IoU
    - Precision
    - Recall
    - FalsePositiveRate
    - TrueNegativeRate
    - F1Score

save_path: ../run_info