name: 00_ResNet18_epoch20
device: cuda
dataset:
  dataset_name: KittiDataset
  task_transform:
    input: 
      # - Crop
    object_detection_2d:
  task_paths:
    input: "./data/kitti/input"
    object_detection_2d: "./data/kitti/object_detection_3d/ground_truth"

train:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1
  aggregators_savers:
    LossAggregator: LossSaver # bind aggregator to saver
  savers:
    LossSaver: LossAggregator # bind aggregator to saver

eval:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1

model:
  encoder:
    name: ResNet18
    pretrained: True
    freeze_epoch: 0
    unfreeze_epoch: 10
  decoder:
    depth:
      name: UnetDepthDecoder
      in_channels: 512
      channel_scale_factors: [2, 4, 8, 8]
      out_channels: 1
      freeze_epoch: None
      unfreeze_epoch: None
  necks_and_heads:
    object_detection_2d:
      name: FPNFasterRCNN
      image_size: [375, 1242] # TODO: set to NEW_H, NEW_W for KITTI
      rpn:
        - training: True
        - num_channels_per_feature_map: [64, 256, 512, 512]
        - objectness_threshold: 0.3
        - iou_threshold: 0.7
        - top_k_proposals_training: 2000
        - top_k_proposals_testing: 300
        - anchor_generator:
          - sizes: [64, 128, 256, 512]
          - aspect_ratios: [0.5, 1, 2]
        - rpn_head:
          - number_of_object_proposals_per_anchor: 3
      roi_network:
        - pool_output_size: [7, 7]

loss:
  depth: 
    - MaskedMAE
  road_detection:
    - BinaryCrossEntropyLoss

optimizer:
  name: Adam
  lr: 1e-4

epochs: 20

metrics:
  depth:
    - MaskedMAE

save_path: ../run_info/