device: cuda
dataset:
  dataset_name: KittiDataset
  task_transform:
    input: 
      - Crop
    object_detection:
  task_paths:
    input: "./data/kitti/input"
    object_detection: "./data/kitti/object_detection/ground_truth"
  task_sample_list_path_train:
    object_detection: "./data/kitti/sample_lists/val/objdet_sample_list.txt"
  task_sample_list_path_val:
    object_detection: "./data/kitti/sample_lists/val/objdet_sample_list.txt"

train:
  dataloader:
    batch_size: 1
    shuffle: True
    num_workers: 1

epochs: 40

early_stopping:
  patience: 5
  min_delta: 0.01

eval:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1

model:
  weights_file_path: ../run_info/01_ResNet18_road_detection_kitti_depth_pretrained/best_model.pth
  encoder:
    name: ResNet18
    pretrained: True
    freeze_epoch: -1
    unfreeze_epoch: 0
    pretrained_regex: ["*"]
  depth_decoder:
    name: UnetDepthDecoder
    in_channels: 512
    channel_scale_factors: [2, 4, 8, 8]
    out_channels: 1
    freeze_epoch: -1
    unfreeze_epoch: 0
    pretrained_regex: ["*"]
  necks_and_heads:
    name: FPNFasterRCNN
    image_size: [256, 1184]
    pool_output_size: [7, 7] # shared between RoI and output heads
    feature_map_names: ["fpn0", "fpn1", "fpn2", "fpn3"]
    num_channels_per_feature_map: [64, 64, 128, 256]
    out_channels: 256
    probability_threshold: 0.1
    iou_threshold: 0.5
    num_classes: 4 # number of classes we are trying to predict + background
    rpn:
      - objectness_threshold: 0.5
      - iou_threshold: 0.7
      - pre_nms_filtering: 6000 # TODO: check https://github.com/open-mmlab/mmdetection/issues/300
      - top_k_proposals_training: 256 # per fpn layer
      - top_k_proposals_testing: 16 # per fpn layer
      - anchor_generator:
        - sizes: [[64], [128], [256], [512]]
        - aspect_ratios: [0.5, 1, 2]
      - rpn_head:
        - number_of_object_proposals_per_anchor: 3
      - freeze_epoch: -1
      - unfreeze_epoch: 0
    roi:
      - sampling_ratio: 4
      - freeze_epoch: -1
      - unfreeze_epoch: 0
    output_heads:
      - score_threshold: 0.3
      - top_k_boxes_training: 256
      - top_k_boxes_testing: 2
      - freeze_epoch: -1
      - unfreeze_epoch: 0
    distance_head:
      - num_conv_layers: 1
      - num_channels: 256
      - num_fc_layers: 2
      - fc_features: 1024
      - freeze_epoch: 0
      - unfreeze_epoch: -1
    attribute_head:
      - num_conv_layers: 1
      - num_channels: 256
      - num_fc_layers: 2
      - fc_features: 1024
      - freeze_epoch: 0
      - unfreeze_epoch: -1

prediction_postprocess: # used only in eval
  - depth:
    - min_depth: 0.0
    - max_depth: 90.0
  - object_detection: # None

loss:
  object_detection:
    - RPNClassificationAndRegressionLoss:
      - scale_factor: 1.0
      - n_cls: 256
      - positives_ratio: 0.25
      - iou_negative_threshold: 0.3
      - iou_positive_threshold: 0.7
      - regularization_factor: 10.0
    - RCNNCrossEntropyAndRegressionLoss:
      - scale_factor: 1.0
      - n_cls: 256
      - positives_ratio: 0.25
      - iou_negative_threshold: 0.2
      - iou_positive_threshold: 0.5
      - regularization_factor: 10.0
      - num_classes: 4

optimizer:
  name: Adam
  lr: 1e-5

metrics:
  object_detection:
    - mAP

save_path: ../run_info/