device: cuda
tasks: ["object_detection_2d"] # for configuring prediction postprocess
dataset:
  dataset_name: KittiDataset
  task_transform:
    input: 
      - Crop
    object_detection_2d:
  task_paths:
    input: "./data/kitti/input"
    object_detection_2d: "./data/kitti/object_detection_3d/ground_truth"

train:
  dataloader:
    batch_size: 1
    shuffle: False
    num_workers: 1
  aggregators_savers:
    LossAggregator: LossSaver # bind aggregator to saver
  savers:
    LossSaver: LossAggregator # bind aggregator to saver

eval:
  dataloader:
    batch_size: 1
    shuffle: True
    num_workers: 1

model:
  encoder:
    name: ResNet18
    pretrained: True
    freeze_epoch: -1
    unfreeze_epoch: -1
  depth_decoder:
    name: UnetDepthDecoder
    in_channels: 512
    channel_scale_factors: [2, 4, 8, 8]
    out_channels: 1
    freeze_epoch: None
    unfreeze_epoch: None
  necks_and_heads:
    object_detection_2d:
      name: FPNFasterRCNN
      image_size: [256, 1184]
      pool_output_size: [7, 7] # shared between RoI and output heads
      num_channels_per_feature_map: [64, 64, 128, 256]
      out_channels: 256
      rpn:
        - objectness_threshold: 0.5
        - iou_threshold: 0.7
        - pre_nms_filtering: 8000 # TODO: check https://github.com/open-mmlab/mmdetection/issues/300
        - top_k_proposals_training: 32 # per fpn layer
        - top_k_proposals_testing: 64 # per fpn layer
        - anchor_generator:
          - sizes: [[64], [128], [256], [512]]
          - aspect_ratios: [0.5, 1, 2]
        - rpn_head:
          - number_of_object_proposals_per_anchor: 3
      roi:
        - feature_map_names: ["fpn0", "fpn1", "fpn2", "fpn3"]
        - sampling_ratio: 4
      output_heads:
        - num_classes: 4 # number of classes we are trying to predict + background
        - score_threshold: 0.3
        - iou_threshold: 0.5
        - top_k_boxes_training: 256
        - top_k_boxes_testing: 20
loss:
  object_detection_2d:
    - RPNClassificationAndRegressionLoss
    - RCNNCrossEntropyAndRegressionLoss
  # object_detection_3d:
optimizer:
  name: Adam
  lr: 1e-4

epochs: 1000

metrics:
  depth:
    - MaskedMAE

save_path: ../run_info/