dataset:
  task_transform:
    input: 
      - ToTensor
      - Crop
    depth: 
      - ToTensor
      - Crop
    objdet:
      - ToTensor
  task_paths:
    input: "./data/kitti/input"
    depth: "./data/kitti/depth/train"
    objdet: "./data/kitti/objdet/train"
