dataset:
  task_transform:
    input: 
      - Crop
    depth: 
      - Crop
  task_paths:
    input: "./data/kitti/input"
    depth: "./data/kitti/depth/train"

model: 
  encoder: ResNet18
  decoder: UnetDecoder

loss:
  depth: 
    - MAE

metrics:
  depth:
    - MAE